# Generated by Django 4.1 on 2024-01-18 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0002_travelrequestheader_thapprovedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverStatus',
            fields=[
                ('THAINTID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel.travelrequestheader')),
            ],
            options={
                'db_table': 'TAS',
            },
        ),
    ]
