# Generated by Django 4.1 on 2024-02-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
